- name: enable pdf edition
  replace:
    path: /etc/ImageMagick-6/policy.xml
    regexp: '(\<policy domain="coder" rights=")(none)(" pattern="PDF" \/\>)'
    replace: '\1read | write\3'
  tags: phpdev
